# Generated by Django 6.0.2 on 2026-02-14 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_bookings_payment'),
        ('payments', '0002_payment_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.bookings'),
        ),
    ]
