# Generated by Django 6.0.2 on 2026-02-15 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='event',
        ),
    ]
