# Generated by Django 6.0.2 on 2026-02-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_payment_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paypal_order_id',
            field=models.CharField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='created', max_length=10),
        ),
    ]
