# Generated by Django 6.0.2 on 2026-02-14 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('host_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_title', models.CharField(max_length=100)),
                ('e_description', models.TextField(max_length=500)),
                ('e_venue', models.CharField(max_length=100)),
                ('e_date', models.DateField()),
                ('e_start_time', models.TimeField()),
                ('e_end_time', models.TimeField()),
                ('e_category', models.CharField(max_length=100)),
                ('total_seats', models.IntegerField()),
                ('price', models.FloatField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host_user.host')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.IntegerField()),
                ('booked', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='events.event')),
            ],
            options={
                'unique_together': {('event', 'seat_no')},
            },
        ),
    ]
