# Generated by Django 6.0.2 on 2026-02-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='e_description',
            field=models.TextField(max_length=3000),
        ),
    ]
