# Generated by Django 6.0.2 on 2026-02-14 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_seats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seats',
            new_name='Seat',
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('event', 'seat_no')},
        ),
    ]
