# Generated by Django 6.0.2 on 2026-02-14 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_seats_seat_alter_seat_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='events.event'),
        ),
    ]
