# Generated by Django 6.0.2 on 2026-02-25 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyeventstable',
            old_name='tickets_sold',
            new_name='seats_sold',
        ),
        migrations.RenameField(
            model_name='eventtotal',
            old_name='total_tickets',
            new_name='total_seats_sold',
        ),
    ]
