# Generated by Django 6.0.2 on 2026-02-25 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_rename_tickets_sold_dailyeventstable_seats_sold_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventtotal',
            old_name='event_id',
            new_name='event',
        ),
    ]
