# Generated by Django 6.0.2 on 2026-03-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='company_contact_no',
            field=models.CharField(max_length=20),
        ),
    ]
