# Generated by Django 6.0.2 on 2026-02-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='payment',
        ),
    ]
